In [1]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import os
import googlemaps
import folium

In [2]:
school_loc = pd.read_csv('../data/폐교관련_인구데이터.csv',encoding = 'cp949')

In [3]:
gmaps_key = 'AIzaSyAK8Ow0bPCO0Vtse5l9dUeNRqjIrp0hiYU'
gmaps = googlemaps.Client(key = gmaps_key)

In [74]:
type(school_loc)

pandas.core.frame.DataFrame

In [31]:
school_loc['주소'][2]

'부산광역시 강서구 천성동 813'

In [79]:
location=gmaps.geocode(school_loc['주소'][394],language='ko')

In [80]:
location

[{'address_components': [{'long_name': '１３５',
    'short_name': '１３５',
    'types': ['premise']},
   {'long_name': '신창리',
    'short_name': '신창리',
    'types': ['political', 'sublocality', 'sublocality_level_3']},
   {'long_name': '한경면',
    'short_name': '한경면',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '제주시',
    'short_name': '제주시',
    'types': ['locality', 'political']},
   {'long_name': '제주특별자치도',
    'short_name': '제주특별자치도',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '695-940',
    'short_name': '695-940',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 제주특별자치도 제주시 한경면 신창리 135',
  'geometry': {'location': {'lat': 33.3477089, 'lng': 126.1850354},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 33.3490578802915,
     'lng': 126.1863843802915},
    'southwest': {'lat': 33.3463599197085, 'lng': 126.1836864197085}}},
  'place_id': 'ChIJLbkxjnxmDDURIx1pOogwMhM',
  'plus_code': {'compound_code': '85XP+32 대한민국 제주특별자치도 제주시 한경면',
   'global_code': '8Q5885XP+32'},
  'types': ['street_address']}]

In [39]:
lat = location[0]['geometry']['location']['lat']
lng = location[0]['geometry']['location']['lng']
print(lat, lng)

35.0688817 128.8411068

In [42]:
lat = location[0]['geometry']['location']['lat']
lng = location[0]['geometry']['location']['lng']
print(lat, lng)

35.00345739999999 128.8310345

In [83]:
arr = np.arange(0,395)

In [86]:
df_lat = []
for num in arr:   
    location = gmaps.geocode(school_loc['주소'][num], language='ko')
    lat = location[0]['geometry']['location']['lat']
    df_lat.append(lat)

In [87]:
df_lat

[35.0688817,
 35.00345739999999,
 35.031595,
 35.2144926,
 35.1815986,
 35.0552935,
 35.6701341,
 37.7704321,
 37.6035228,
 37.5273686,
 37.718577,
 37.676569,
 37.676569,
 36.4053001,
 35.686006,
 35.4394789,
 36.4666136,
 37.10092900000001,
 37.8102323,
 37.7765321,
 37.20241650000001,
 37.3980906,
 37.9137075,
 37.9246947,
 37.1710576,
 37.7048829,
 37.7946862,
 38.0543052,
 37.284927,
 37.6517124,
 38.116174,
 37.6672988,
 37.2244672,
 37.3199489,
 37.97759569999999,
 38.0282545,
 37.34804159999999,
 37.2572179,
 37.2077982,
 37.2771775,
 37.2602026,
 37.3965161,
 37.3818445,
 37.5278069,
 37.1536891,
 37.7096868,
 37.9882814,
 37.477872,
 37.4418473,
 37.4056625,
 37.827806,
 37.5667542,
 37.2198632,
 37.118846,
 37.2311203,
 37.2897228,
 37.2311203,
 37.1989792,
 37.55879669999999,
 37.5914713,
 37.3223514,
 37.3269478,
 37.37976889999999,
 37.2940174,
 38.0032383,
 37.7472346,
 36.8442389,
 37.0425466,
 36.8932442,
 36.8860035,
 36.8886534,
 36.9277034,
 36.9880856,
 36.6361403,
 36.6510445,
 36.902477,
 36.9266241,
 36.1435169,
 36.1072466,
 36.8523181,
 36.9238013,
 36.5462971,
 36.5410654,
 36.490919,
 36.9055961,
 37.1624159,
 36.15297290000001,
 37.0615791,
 37.0657462,
 36.6460078,
 36.735882,
 36.6886943,
 36.2654235,
 36.9142487,
 36.9238652,
 36.7876672,
 37.0614156,
 36.8443154,
 36.3297499,
 36.2767112,
 36.3487447,
 36.7432671,
 36.730596,
 36.2308733,
 36.4218081,
 36.6602332,
 36.1232057,
 36.1602335,
 36.6392761,
 36.5289235,
 36.3686748,
 36.409169,
 36.6490523,
 36.5712706,
 36.5746179,
 36.4921122,
 36.4974825,
 36.5035564,
 36.5166584,
 36.505452,
 36.2116429,
 36.3998203,
 36.0761902,
 36.9322447,
 36.64143749999999,
 36.81053259999999,
 36.1717013,
 36.2597711,
 36.7380934,
 36.1354625,
 36.3874329,
 36.1818801,
 36.4860024,
 36.4538896,
 36.3092175,
 36.1077914,
 36.7212255,
 35.8158753,
 35.84989059999999,
 36.0810681,
 35.5768845,
 35.6586342,
 35.6435316,
 35.1438716,
 34.6128226,
 35.2620616,
 34.9423036,
 34.6840847,
 35.2403855,
 34.4662935,
 35.34222460000001,
 34.4967722,
 34.4406901,
 34.5644581,
 34.5798033,
 35.0228465,
 34.2054318,
 34.895447,
 34.9939453,
 35.1987863,
 35.1237372,
 35.08485870000001,
 35.0129974,
 34.8712958,
 34.4808046,
 34.5070253,
 34.5991317,
 34.6629779,
 34.6056868,
 34.9991187,
 34.6003735,
 34.6329182,
 34.6389835,
 35.0718486,
 35.0301738,
 35.2969357,
 34.8471775,
 34.7972038,
 35.3461195,
 34.864504,
 34.8453242,
 34.1353614,
 34.467822,
 34.9859023,
 35.3864804,
 35.40714850000001,
 34.6910116,
 35.0505684,
 34.2267913,
 34.0253788,
 34.0560117,
 34.2267913,
 34.1732689,
 34.9327828,
 35.0235715,
 34.9509083,
 34.7965174,
 34.17494120000001,
 35.1312636,
 34.8987156,
 34.9288277,
 34.8611142,
 35.229597,
 35.3066211,
 34.8031423,
 35.0099187,
 34.9132439,
 34.7170403,
 34.8804206,
 34.9243387,
 34.869769,
 34.3798848,
 35.3268765,
 34.6512512,
 34.2350193,
 34.2115171,
 34.2538797,
 35.097511,
 35.1351905,
 35.0529457,
 35.0345995,
 34.8561961,
 34.9243975,
 34.9398108,
 35.2041561,
 35.0320514,
 35.0579946,
 35.1121464,
 35.1132014,
 35.0191063,
 34.9936805,
 35.0603603,
 35.4065088,
 35.4020256,
 34.4518897,
 35.0875091,
 34.7330023,
 34.5909732,
 35.1271709,
 35.1899733,
 36.2361372,
 35.6904911,
 36.2036028,
 36.3796971,
 35.7190865,
 35.7972503,
 36.003369,
 36.0065038,
 36.5103023,
 35.9626393,
 36.0352547,
 36.3524263,
 36.8945032,
 36.2613049,
 35.9261511,
 35.690129,
 36.06892029999999,
 35.7686684,
 35.7382741,
 35.7472998,
 36.7447808,
 35.8419533,
 36.806221,
 36.2554328,
 36.9341123,
 36.9380692,
 36.9108527,
 35.8763295,
 36.8810061,
 35.9868862,
 35.8736219,
 35.6965857,
 36.8324538,
 35.9332196,
 36.3063212,
 35.81579139999999,
 36.0654521,
 36.1547556,
 36.0218116,
 36.4112771,
 36.4323542,
 36.4975722,
 36.0929046,
 35.6690376,
 36.445653,
 36.4094501,
 36.6939735,
 36.6417751,
 36.3456751,
 36.3107221,
 36.8366888,
 36.0205563,
 36.0496815,
 36.0569475,
 36.5705212,
 36.5907756,
 36.0665555,
 37.0538439,
 36.2923875,
 36.4180283,
 35.9090477,
 35.9970141,
 35.9970141,
 36.451462,
 37.0579097,
 36.1773133,
 36.0478445,
 36.1009249,
 36.1534672,
 35.3796616,
 35.76134440000001,
 35.7504345,
 35.7317012,
 35.8220996,
 35.3753348,
 34.8899117,
 35.1193662,
 35.0993758,
 35.0692372,
 35.4365373,
 34.9743925,
 35.4588891,
 34.7613044,
 34.7080183,
 35.62270609999999,
 35.2602741,
 35.34467,
 35.3419847,
 35.425255,
 34.7845529,
 34.9353582,
 34.9448493,
 34.9219408,
 35.0153341,
 35.029914,
 35.4996228,
 35.166914,
 34.7120127,
 35.3004116,
 35.557503,
 35.6358454,
 35.1124373,
 35.1141333,
 34.8459346,
 34.8173824,
 34.7679351,
 34.8231859,
 34.8308881,
 34.7980977,
 34.9555877,
 35.1778148,
 35.2130817,
 35.0588021,
 35.0443608,
 35.1838141,
 35.4574285,
 35.4189722,
 34.6758315,
 34.7020969,
 34.637232,
 35.7564956,
 35.4184575,
 35.4499935,
 34.8079884,
 34.801805,
 34.9725087,
 35.0822985,
 35.03133040000001,
 35.7664263,
 35.2452726,
 35.236152,
 35.1935285,
 35.3998352,
 35.0057336,
 35.1506928,
 35.2487929,
 35.5204183,
 34.8971119,
 35.4089381,
 34.9127333,
 34.9607055,
 35.3445519,
 34.7840593,
 34.7104474,
 34.7499612,
 34.7968971,
 35.4816034,
 35.2291204,
 35.0842522,
 35.4651731,
 35.0972835,
 33.5038083,
 33.3830571,
 33.956025,
 33.3477089]

In [89]:
df_lng = []
for num in arr:
    location = gmaps.geocode(school_loc['주소'][num], language='ko')
    lng = location[0]['geometry']['location']['lng']
    df_lng.append(lng)

In [90]:
df_lng

[128.8411068,
 128.8310345,
 128.8133089,
 128.9352088,
 128.9782813,
 128.8047273,
 128.454797,
 126.2391837,
 126.489544,
 126.4525008,
 126.2321508,
 126.1746742,
 126.1746742,
 127.4742927,
 129.1645621,
 129.2277516,
 127.2816256,
 127.2913047,
 126.9289713,
 126.9077538,
 127.4483502,
 127.679035,
 127.5896846,
 127.4907425,
 126.6224067,
 127.4481826,
 127.0109724,
 127.2724834,
 127.1407046,
 127.2861319,
 127.2943007,
 129.0416628,
 127.8635287,
 129.2193943,
 128.055184,
 128.0765088,
 129.1633808,
 129.1783293,
 129.0780875,
 129.0622637,
 129.1117727,
 129.0855407,
 129.0942055,
 128.3352339,
 127.7867832,
 127.7998743,
 127.8482031,
 127.8135633,
 129.1143734,
 128.131836,
 128.6553172,
 128.431552,
 129.3186944,
 129.2615478,
 128.2787635,
 128.2391986,
 128.2787635,
 128.6145417,
 128.5627747,
 128.2193204,
 128.3355523,
 128.3694741,
 128.8954072,
 128.8813314,
 128.6306267,
 128.0443062,
 127.7957275,
 127.8002203,
 128.3054919,
 127.4808286,
 127.5089142,
 128.1437654,
 128.0547576,
 127.6584171,
 127.4870295,
 127.8175781,
 127.9342571,
 127.9131592,
 127.9176753,
 127.693081,
 127.75187,
 127.787057,
 127.7864962,
 127.8601455,
 128.2414829,
 127.7521631,
 127.6314236,
 128.5516737,
 128.6125791,
 127.3141782,
 127.3661168,
 127.4042218,
 127.8233701,
 127.6235737,
 127.4666395,
 127.9155426,
 127.8614049,
 127.3542807,
 127.8152421,
 127.7322573,
 127.737616,
 127.6983207,
 127.7967824,
 127.9088922,
 127.578102,
 127.4287824,
 127.1572992,
 127.190541,
 126.5302269,
 126.5501575,
 127.1652106,
 126.4216753,
 126.5053084,
 126.7811804,
 126.8139122,
 126.6178592,
 126.6299197,
 126.6348793,
 126.6618353,
 126.6249503,
 126.8055018,
 126.7441007,
 127.5151904,
 126.5136068,
 126.8414866,
 127.3178477,
 127.4314514,
 126.9524852,
 126.1347686,
 126.8824583,
 127.0787624,
 126.8980566,
 126.6779877,
 126.8009822,
 127.0051085,
 126.8298531,
 126.5409518,
 126.3727645,
 126.3727645,
 126.4359283,
 126.2494216,
 126.108259,
 126.1194039,
 127.0616011,
 126.7261659,
 127.2729386,
 126.6181706,
 127.3278162,
 126.4525854,
 127.1300781,
 126.0301831,
 127.7827941,
 127.8040494,
 127.7485093,
 127.7599025,
 126.8636445,
 126.6028356,
 126.8291687,
 126.6163534,
 127.0930522,
 126.4945325,
 126.5607413,
 126.939811,
 126.6474856,
 127.3086973,
 127.3600273,
 127.770695,
 127.7724742,
 127.74562,
 127.0177467,
 126.3514721,
 126.3486212,
 126.3070726,
 126.6520469,
 126.6107253,
 126.4501299,
 127.3646497,
 127.4640499,
 126.5060019,
 127.4643206,
 127.4515476,
 126.568514,
 127.4599959,
 126.7842472,
 126.7926195,
 126.8806327,
 126.3627438,
 126.8125867,
 127.2386939,
 127.3033056,
 127.2966414,
 127.2386939,
 127.3543852,
 127.4145166,
 127.502198,
 126.7381097,
 127.5998417,
 126.6517772,
 126.4743775,
 126.6087076,
 126.6790086,
 126.1241857,
 126.3188146,
 126.48562,
 126.7982576,
 127.6189105,
 127.2757123,
 127.0213703,
 127.6178334,
 126.996259,
 126.4754816,
 126.1906012,
 127.2246434,
 127.4459093,
 125.9374767,
 125.8571193,
 125.9076704,
 127.2370201,
 127.2847999,
 127.6879375,
 127.75608,
 126.9407966,
 126.9325136,
 127.7485863,
 127.6036325,
 126.5353162,
 126.5208713,
 126.2884413,
 126.3182817,
 126.4042457,
 126.436674,
 126.4637043,
 126.4199107,
 126.4727095,
 126.484441,
 127.0155059,
 126.2998641,
 127.688515,
 127.4679619,
 127.1691854,
 128.7227549,
 128.5885493,
 128.2198678,
 129.3635356,
 128.4130182,
 129.1382384,
 129.0671895,
 129.0974236,
 128.1548205,
 129.5161227,
 128.0549128,
 128.412941,
 129.2536363,
 128.6864453,
 128.0967799,
 128.8944974,
 128.2665485,
 129.1105938,
 129.2027442,
 129.1295465,
 128.7753411,
 128.4132866,
 128.8869875,
 128.2235716,
 128.7398456,
 128.6787341,
 128.8704162,
 129.327562,
 128.8191638,
 127.9419879,
 128.9950401,
 129.0574092,
 128.7565895,
 128.3930812,
 128.4669477,
 128.2313648,
 128.7311424,
 128.1958363,
 129.2255725,
 128.4319832,
 128.4685992,
 128.4231793,
 128.1060711,
 129.4246988,
 129.42186,
 129.4277108,
 128.9160122,
 128.7715386,
 128.0796128,
 128.6777838,
 128.6966476,
 128.9820278,
 129.0302643,
 129.1104004,
 128.919315,
 129.0869613,
 129.0735249,
 129.3880918,
 129.2584203,
 128.2836969,
 128.0259298,
 128.0318703,
 128.0318703,
 129.2330537,
 128.7967951,
 128.4105684,
 129.5732447,
 128.8638025,
 128.919997,
 128.231271,
 127.9908446,
 128.1278917,
 128.1071687,
 128.1179362,
 129.0280464,
 127.8741071,
 128.581151,
 128.5650018,
 128.6236009,
 128.2326164,
 127.8852934,
 127.792608,
 127.8571528,
 128.6182368,
 127.9752582,
 128.5415184,
 128.4488259,
 128.4126711,
 128.5307765,
 128.5725451,
 128.0326256,
 128.0427835,
 128.0411945,
 128.442774,
 128.3570393,
 128.6816143,
 128.1671145,
 128.0417335,
 128.1154848,
 127.7110071,
 128.0687359,
 127.8568693,
 127.8900051,
 128.1791091,
 128.2440766,
 128.4217054,
 128.3718679,
 128.004195,
 128.0460014,
 128.2401086,
 128.1015379,
 127.8965016,
 127.8569235,
 127.848718,
 128.4318291,
 128.5241011,
 128.4829121,
 128.2341623,
 128.1838556,
 128.260244,
 127.8341167,
 128.2861491,
 127.7785118,
 128.6938714,
 128.7191587,
 128.6948068,
 127.7844285,
 128.1609704,
 127.9482676,
 128.8365317,
 128.8215732,
 128.0950654,
 128.407721,
 127.9122301,
 128.3706202,
 128.1251739,
 128.5589227,
 127.993992,
 128.6961837,
 128.1791754,
 128.6178363,
 128.8122543,
 128.4798577,
 128.4586113,
 128.4941168,
 128.5052898,
 127.6893411,
 128.8761743,
 128.3741401,
 127.7597319,
 128.7205987,
 126.6103425,
 126.8724832,
 126.2933464,
 126.1850354]

In [91]:
df_lat = pd.DataFrame(df_lat, columns=['lat'])

In [92]:
df_lng = pd.DataFrame(df_lng, columns=['lng'])
df_lng

            lng
0    128.841107
1    128.831034
2    128.813309
3    128.935209
4    128.978281
5    128.804727
6    128.454797
7    126.239184
8    126.489544
9    126.452501
10   126.232151
11   126.174674
12   126.174674
13   127.474293
14   129.164562
15   129.227752
16   127.281626
17   127.291305
18   126.928971
19   126.907754
20   127.448350
21   127.679035
22   127.589685
23   127.490742
24   126.622407
25   127.448183
26   127.010972
27   127.272483
28   127.140705
29   127.286132
..          ...
365  128.694807
366  127.784429
367  128.160970
368  127.948268
369  128.836532
370  128.821573
371  128.095065
372  128.407721
373  127.912230
374  128.370620
375  128.125174
376  128.558923
377  127.993992
378  128.696184
379  128.179175
380  128.617836
381  128.812254
382  128.479858
383  128.458611
384  128.494117
385  128.505290
386  127.689341
387  128.876174
388  128.374140
389  127.759732
390  128.720599
391  126.610343
392  126.872483
393  126.293346
394  126.185035

[395 rows x 1 columns]

In [93]:
df_loc = pd.concat([df_lat,df_lng], axis=1)

In [94]:
df_loc

           lat         lng
0    35.068882  128.841107
1    35.003457  128.831034
2    35.031595  128.813309
3    35.214493  128.935209
4    35.181599  128.978281
5    35.055293  128.804727
6    35.670134  128.454797
7    37.770432  126.239184
8    37.603523  126.489544
9    37.527369  126.452501
10   37.718577  126.232151
11   37.676569  126.174674
12   37.676569  126.174674
13   36.405300  127.474293
14   35.686006  129.164562
15   35.439479  129.227752
16   36.466614  127.281626
17   37.100929  127.291305
18   37.810232  126.928971
19   37.776532  126.907754
20   37.202417  127.448350
21   37.398091  127.679035
22   37.913708  127.589685
23   37.924695  127.490742
24   37.171058  126.622407
25   37.704883  127.448183
26   37.794686  127.010972
27   38.054305  127.272483
28   37.284927  127.140705
29   37.651712  127.286132
..         ...         ...
365  34.972509  128.694807
366  35.082299  127.784429
367  35.031330  128.160970
368  35.766426  127.948268
369  35.245273  128.836532
370  35.236152  128.821573
371  35.193528  128.095065
372  35.399835  128.407721
373  35.005734  127.912230
374  35.150693  128.370620
375  35.248793  128.125174
376  35.520418  128.558923
377  34.897112  127.993992
378  35.408938  128.696184
379  34.912733  128.179175
380  34.960706  128.617836
381  35.344552  128.812254
382  34.784059  128.479858
383  34.710447  128.458611
384  34.749961  128.494117
385  34.796897  128.505290
386  35.481603  127.689341
387  35.229120  128.876174
388  35.084252  128.374140
389  35.465173  127.759732
390  35.097284  128.720599
391  33.503808  126.610343
392  33.383057  126.872483
393  33.956025  126.293346
394  33.347709  126.185035

[395 rows x 2 columns]

In [95]:
loc = pd.concat([school_loc,df_loc], axis=1)

In [96]:
loc.to_csv(r'C:\Users\GREEN\data\폐교_인구_위도경도.csv', sep=',',encoding='cp949',index=False)